### ISSUE TITLE
Unable to save page, python binary string not binary

### ISSUE THREAD

**Issue by gabefair** [internetarchive/wayback#215]
![image](https://user-images.githubusercontent.com/2096785/79237124-ca465a80-7e3b-11ea-87e8-df7b3c86e2a4.png)

This screenshot was taken 2 mins ago.

**Comment by vbanos** [comment]
http://fda.gov doesn't work, they haven't configured their servers to redirect to http://www.fda.gov automatiically. Please try to capture http://www.fda.gov.

Also note that Chrome has a new "feature" to present `www.fda.gov` as `fda.gov` (they hide the `www.` part). Maybe this is also contributing to the confusion.

As for the binary string, thank you for noticing it, it will be fixed in the next service update.
