### ISSUE TITLE
matchType=domain doesn't work as expected

### ISSUE THREAD

**Issue by chemiron** [internetarchive/wayback#93]
Hi,
I want to get all archived pages for domain and all its subdomains. So I'm using the following url:

http://web.archive.org/cdx/search/cdx?url=*.tut.by&from=20150724&to=20150724&filter=mimetype:text/html&output=json&fl=timestamp,original

There are no records for subdomain news.tut.by. But if I try the following url I'll get a lot of records for subdomain news.tut.by:

http://web.archive.org/cdx/search/cdx?url=*.news.tut.by&from=20150724&to=20150724&filter=mimetype:text/html&output=json&fl=timestamp,original

Thanks

**Comment by kngenie** [comment]
This is due to a limit on the number of CDX lines that can be scanned in one query: maximum 160 CDX blocks (3000 lines each) per query. `*.tut.by` spans across 3811 blocks, and `news.tut.by` starts at block 3043. CDX server does not get to `news.tut.by` records as it cuts off query result at 160th block. This seemingly arbitrary limit is to prevent large query from swamping Wayback. I wish it could at least issue a warning when this happens.

For querying for domain with large number of captures, I'd recommend using [Pagination API](https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server#pagination-api) instead.

**Comment by chemiron** [comment]
I've tried pagination, but it looks like it doesn't work with from/to filter. E.g. the follow url returns nothing:
http://web.archive.org/cdx/search/cdx?url=archive.org&from=2011&page=0
But there exists results for 2011 year.

**Comment by kngenie** [comment]
block 0 of `archive.org` only contains records for year 1997-2001. `page=29` will give some results.
That is, `from`/`to` filter is applied _after_ picking a block to scan. Pagination is clearly a misnomer.

**Comment by chemiron** [comment]
Is there any ability to retrieve all records with subdomains filtered by some conditions? or I should retrieve all records using 'pagination' and then apply filters in my source code ?

**Comment by kngenie** [comment]
Filters _do_ work with pagination mode. Wayback retrieves the block specified, and then applies filters to each CDX line in the block. So you need to loop over all blocks and make queries with filter, some of which may return empty result. It is designed like this for processing with Hadoop map-reduce jobs.

**Comment by chemiron** [comment]
Thanks
